2018-12-19 20:26:23,727 ERROR: Exception on /user/nishishui [GET][in e:\myproject\gui\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\myproject\gui\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\myproject\gui\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\MyProject\Python\microblog\app\main\routes.py", line 75, in user
    next_url=next_url, prev_url=prev_url)
  File "e:\myproject\gui\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "e:\myproject\gui\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "E:\MyProject\Python\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\MyProject\Python\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "e:\myproject\gui\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "e:\myproject\gui\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "e:\myproject\gui\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "e:\myproject\gui\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "E:\MyProject\Python\microblog\app\templates\base.html", line 55, in block "content"
    {% block app_content %}{% endblock %}
  File "E:\MyProject\Python\microblog\app\templates\user.html", line 15, in block "app_content"
    <p><a href="{{ url_for('edit_profile') }}">{{ _('Edit your profile') }}</a></p>
  File "e:\myproject\gui\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "e:\myproject\gui\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "e:\myproject\gui\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "e:\myproject\gui\venv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'main.edit_profile' instead?
2018-12-19 20:26:54,399 INFO: Microblog startup[in E:\MyProject\Python\microblog\app\__init__.py:78]
2018-12-19 20:27:00,841 ERROR: Exception on /user/nishishui [GET][in e:\myproject\gui\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\myproject\gui\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\myproject\gui\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\MyProject\Python\microblog\app\main\routes.py", line 75, in user
    next_url=next_url, prev_url=prev_url)
  File "e:\myproject\gui\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "e:\myproject\gui\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "e:\myproject\gui\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "E:\MyProject\Python\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\MyProject\Python\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "e:\myproject\gui\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "e:\myproject\gui\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "e:\myproject\gui\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "e:\myproject\gui\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "E:\MyProject\Python\microblog\app\templates\base.html", line 55, in block "content"
    {% block app_content %}{% endblock %}
  File "E:\MyProject\Python\microblog\app\templates\user.html", line 15, in block "app_content"
    <p><a href="{{ url_for('edit_profile') }}">{{ _('Edit your profile') }}</a></p>
  File "e:\myproject\gui\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "e:\myproject\gui\venv\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "e:\myproject\gui\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "e:\myproject\gui\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "e:\myproject\gui\venv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'main.edit_profile' instead?
2018-12-19 20:31:22,825 INFO: Microblog startup[in E:\MyProject\Python\microblog\app\__init__.py:78]
